name: diagnostico-analisis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas>=1.5.0
  - numpy>=1.23.0
  - scipy>=1.9.0
  - statsmodels>=0.13.0
  - scikit-learn>=1.1.0
  - matplotlib>=3.6.0
  - seaborn>=0.12.0
  - plotly>=5.10.0
  - jupyter>=1.0.0
  - jupyterlab>=3.5.0
  - notebook>=6.5.0
  - ipywidgets>=8.0.0
  - openpyxl>=3.0.10
  - xlsxwriter>=3.0.3
  - tqdm>=4.64.0
  - pip
  - pip:
    - []
